### ISSUE TITLE
FAIR score not present for new resources

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#135]
We have added several new resources, but the FAIR score was not calculated:
* https://ecoportal.lifewatchdev.eu/ontologies/PALEO_VARIABLES
* https://ecoportal.lifewatchdev.eu/ontologies/ARCHIVE
* https://ecoportal.lifewatchdev.eu/ontologies/TRAITS_THES

... and more.

**Comment by syphax-bouazzouni** [comment]
Fixed, for example with PALEO_VARIABLES.
![image](https://github.com/user-attachments/assets/8690a537-c769-4285-a834-e594468cf512)

For reference new resources get their fair score calculated 24 hours after the submission.

**Comment by martinaPulieri** [comment]
it is still not showing in the semantic resource summary page.

**Comment by syphax-bouazzouni** [comment]
Hello @martinaPulieri, I think it is just a cache issue, you can try again now, you should see it
https://ecoportal.lifewatchdev.eu/ontologies/PALEO_VARIABLES  
![image](https://github.com/user-attachments/assets/5efb001c-1b42-4d28-8cb5-93e0169a7ffd)

I let you close if done
