### ISSUE TITLE
[Collection] Error 404 when browsing

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#162]
Link to collection is not working (404 error) in the concepts tab.

<img width="1577" height="806" alt="Image" src="https://github.com/user-attachments/assets/87e60dd8-876a-4633-b1a2-d0ad85d8cad9" />

<img width="1569" height="911" alt="Image" src="https://github.com/user-attachments/assets/20d681f8-06f6-497b-8582-4dfbf49bbd4f" />

**Comment by jonquet** [comment]
Indeed? I ca't reporodduce as the resource is private, but this should open the Collection tab

**Comment by MikeGriniezakis** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/pull/189

**Comment by martinaPulieri** [comment]
The error is still there. I have uploaded the resource on the dev machine. It is here: https://ecoportal.lifewatchdev.eu/ontologies/AGRIPOD

**Comment by MikeGriniezakis** [comment]
Could you give me an example? Pressing on the Member Of entry correctly redirects me:

<img width="1340" height="721" alt="Image" src="https://github.com/user-attachments/assets/e418716b-ba9c-412b-b30d-f7913cda16d1" />

 https://ecoportal.lifewatchdev.eu/ontologies/AGRIPOD?p=classes&conceptid=http%3A%2F%2Fdata.europa.eu%2F3t3%2Fagriprod%2FARA09S

**Comment by martinaPulieri** [comment]
This is not working in the production machine. Maybe it is fixed now?

**Comment by MikeGriniezakis** [comment]
I have updated production and tested it there as well and it seems to work as intended.
