### ISSUE TITLE
Concepts IDs - hyperlinks

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#25]
ID of concepts are not hyperlinks

<img width="1141" alt="Screenshot 2023-09-19 alle 14 57 45" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/6b07af4e-6976-444e-b994-5fb3887b52c9">

**Comment by jonquet** [comment]
This is actually a feature. 
Most of the time these IDs are URIs not necessarily resolvable (i.e. that will point to a vlaid URL). So its to avoid people to think the portal is full of broken links. 

In other words, IDs look like links but they are not necessariy. And if they are ... they get people out of EcoPortal.

Next UI release is supposed to include a ay to activate the links when they are actually resolvable. And also show a little arrow out that will tell the user he/she will be going out of the portal when clicking.

**Comment by syphax-bouazzouni** [comment]
Fixed in #28 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/a2afb5f9-5b36-4927-b3de-693924737625)

**Comment by jonquet** [comment]
Be sure to open this link in ANOTHER tab, so its explicit that its not OntoPortal having a problem if the URI does not resolve.
