### ISSUE TITLE
Email change

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#62]
Change the email from [service.centre@lifewatch.eu] to [semantics@lifewatch.eu].

**Comment by syphax-bouazzouni** [comment]
Done
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/ffcc5e7d-9b6a-4168-9750-3d9c0885f4fe)

**Comment by martinaPulieri** [comment]
I still see service.centre@lifewatch.eu

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/550fe07a-802a-4586-8eeb-948571d19f2d)

**Comment by syphax-bouazzouni** [comment]
You can check again, now it's done.
